"""Provider-free episodic retrieval with optional transient head signals."""

from .boundaries import (
    AdaptiveBoundaryDetector,
    BoundaryDetector,
    BoundaryProposal,
    BoundaryRefinement,
    CohesionBoundaryRefiner,
    FixedIntervalBoundaryDetector,
)
from .builder import EpisodeBuildResult, EpisodeBuilder
from .representatives import select_episode_representatives
from .representative_prefilter import (
    EpisodeRepresentativeEmbedding,
    EpisodeRepresentativePrefilterPolicy,
    EpisodeRepresentativePrefilterReceipt,
    EpisodeRepresentativePrefilterResult,
    EpisodeRepresentativePrefilterTiming,
    prefilter_episode_representatives,
    prefilter_prescored_episode_representatives,
)
from .descriptor_index import (
    EpisodeDescriptorCatalogReceipt,
    EpisodeDescriptorEnsureResult,
    EpisodeDescriptorIndex,
    EpisodeDescriptorIndexUnavailable,
    EpisodeDescriptorScoreResult,
)
from .representative_retrieval import (
    EpisodeRepresentativeLookup,
    EpisodeRepresentativeRetrievalPlan,
    EpisodeRepresentativeRetrievalPolicy,
    EpisodeRepresentativeWitness,
    EpisodeSourceCandidate,
    EpisodeSourceCandidateScope,
    EpisodeSourceScan,
    NestedEpisodeLinker,
    RepresentativeHydrator,
    episode_source_candidates_from_results,
    retrieve_episode_representatives,
)
from .retrieval import (
    DirectChunkSeed,
    EpisodeLookup,
    EpisodeRetrievalPlan,
    EpisodeRetrievalPolicy,
    combine_episode_seeds,
    episode_seed_payload,
    expand_episode_seeds,
)
from .surprise import (
    ATTENTION_HEAD_SIMILARITY_ALGORITHM,
    ATTENTION_HEAD_SURPRISE_ALGORITHM,
    ATTENTION_HEAD_SURPRISE_FORMAT,
    ATTENTION_HEAD_SURPRISE_SCORE_FORMULA,
    EPISODIC_SURPRISE_PROBE,
    AttentionHeadSurpriseReceipt,
    LexicalEmbeddingChangeScorer,
    QwenAttentionHeadSurpriseScorer,
    ScoredSurpriseSequence,
    SurpriseScorer,
    SurpriseSequenceScorer,
    dense_cosine,
    lexical_cosine,
    score_surprise_sequence,
)
from .user_led import (
    ORPHAN_PRELUDE_BOUNDARY_METHOD,
    USER_LED_BOUNDARY_METHOD,
    USER_LED_EPISODE_FORMAT,
    UserLedEpisodeBuildResult,
    UserLedEpisodeBuilder,
    UserLedEpisodeShard,
    build_user_led_episodes,
    make_user_led_exchange_id,
)


__all__ = [
    "ATTENTION_HEAD_SIMILARITY_ALGORITHM",
    "ATTENTION_HEAD_SURPRISE_ALGORITHM",
    "ATTENTION_HEAD_SURPRISE_FORMAT",
    "ATTENTION_HEAD_SURPRISE_SCORE_FORMULA",
    "AdaptiveBoundaryDetector",
    "AttentionHeadSurpriseReceipt",
    "BoundaryDetector",
    "BoundaryProposal",
    "BoundaryRefinement",
    "CohesionBoundaryRefiner",
    "DirectChunkSeed",
    "EPISODIC_SURPRISE_PROBE",
    "EpisodeBuildResult",
    "EpisodeBuilder",
    "EpisodeDescriptorCatalogReceipt",
    "EpisodeDescriptorEnsureResult",
    "EpisodeDescriptorIndex",
    "EpisodeDescriptorIndexUnavailable",
    "EpisodeDescriptorScoreResult",
    "EpisodeLookup",
    "EpisodeRepresentativeLookup",
    "EpisodeRepresentativeEmbedding",
    "EpisodeRepresentativePrefilterPolicy",
    "EpisodeRepresentativePrefilterReceipt",
    "EpisodeRepresentativePrefilterResult",
    "EpisodeRepresentativePrefilterTiming",
    "EpisodeRepresentativeRetrievalPlan",
    "EpisodeRepresentativeRetrievalPolicy",
    "EpisodeRepresentativeWitness",
    "EpisodeRetrievalPlan",
    "EpisodeRetrievalPolicy",
    "EpisodeSourceCandidate",
    "EpisodeSourceCandidateScope",
    "EpisodeSourceScan",
    "FixedIntervalBoundaryDetector",
    "LexicalEmbeddingChangeScorer",
    "NestedEpisodeLinker",
    "ORPHAN_PRELUDE_BOUNDARY_METHOD",
    "QwenAttentionHeadSurpriseScorer",
    "ScoredSurpriseSequence",
    "RepresentativeHydrator",
    "SurpriseScorer",
    "SurpriseSequenceScorer",
    "USER_LED_BOUNDARY_METHOD",
    "USER_LED_EPISODE_FORMAT",
    "UserLedEpisodeBuildResult",
    "UserLedEpisodeBuilder",
    "UserLedEpisodeShard",
    "build_user_led_episodes",
    "combine_episode_seeds",
    "dense_cosine",
    "episode_source_candidates_from_results",
    "episode_seed_payload",
    "expand_episode_seeds",
    "lexical_cosine",
    "make_user_led_exchange_id",
    "prefilter_episode_representatives",
    "prefilter_prescored_episode_representatives",
    "retrieve_episode_representatives",
    "score_surprise_sequence",
    "select_episode_representatives",
]
